

-- USER Table
CREATE TABLE USER (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_FNAME VARCHAR(50) NOT NULL,
    USER_MNAME VARCHAR(50),
    USER_LNAME VARCHAR(50) NOT NULL,
    USER_EMAIL VARCHAR(100) UNIQUE NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    USER_PHONE VARCHAR(15),
    USER_ROLE VARCHAR(20),
    USER_STATUS VARCHAR(20),
    USER_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_IS_ONLINE BOOLEAN DEFAULT 0
);

-- AGENT_STATUS Table
CREATE TABLE AGENT_STATUS (
    LOGIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- LOGIN_HISTORY Table
CREATE TABLE LOGIN_HISTORY (
    LOGIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOGIN_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- USER_UPDATE_HISTORY Table
CREATE TABLE USER_UPDATE_HISTORY (
    UPDATE_ID INT AUTO_INCREMENT PRIMARY KEY,
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- ADDRESS Table
CREATE TABLE ADDRESS (
    ADDRESS_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ADDRESS_TYPE VARCHAR(50),
    ADDRESS_REGION VARCHAR(50),
    ADDRESS_PROVINCE VARCHAR(50),
    ADDRESS_CITY VARCHAR(50),
    ADDRESS_BARANGAY VARCHAR(50),
    ADDRESS_STREET VARCHAR(100),
    ADDRESS_ZIPCODE VARCHAR(10),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

-- CAR Table
CREATE TABLE CAR (
    CAR_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_DESCRIPTION TEXT,
    CAR_BRAND VARCHAR(50),
    CAR_MODEL VARCHAR(50),
    CAR_YEAR YEAR,
    CAR_TYPE VARCHAR(50),
    CAR_COLOR VARCHAR(30),
    CAR_LICENSE_PLATE VARCHAR(20),
    CAR_VIN VARCHAR(50),
    CAR_SEATS INT,
    CAR_TRANSMISSION_TYPE VARCHAR(20),
    CAR_FUEL_TYPE VARCHAR(30),
    CAR_RENTAL_RATE DECIMAL(10, 2),
    CAR_AVAILABILITY BOOLEAN DEFAULT 1,
    CAR_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CAR_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- CAR_IMAGE Table
CREATE TABLE CAR_IMAGE (
    IMG_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_ID INT,
    IMG_URL VARCHAR(255),
    IMG_DESCRIPTION TEXT,
    IMG_POSITION INT,
    IS_PRIMARY BOOLEAN DEFAULT 0,
    IMG_UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID)
);

-- DRIVER Table
CREATE TABLE DRIVER (
    DRIVER_ID INT AUTO_INCREMENT PRIMARY KEY,
    DRIVER_NAME VARCHAR(100) NOT NULL,
    DRIVER_PHONE VARCHAR(15),
    DRIVER_LICENSE_NUMBER VARCHAR(50),
    DRIVER_AVAILABILITY BOOLEAN DEFAULT 1,
    DRIVER_CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DRIVER_UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- RENTAL Table
CREATE TABLE RENTAL (
    RENTAL_ID INT AUTO_INCREMENT PRIMARY KEY,
    CAR_ID INT,
    USER_ID INT,
    ASSIGNED_DRIVER_ID INT NULL,
    IS_CUSTOM_DRIVER BOOLEAN DEFAULT 0,
    CUSTOM_DRIVER_NAME VARCHAR(100),
    CUSTOM_DRIVER_PHONE VARCHAR(15),
    CUSTOM_DRIVER_LICENSE_NUMBER VARCHAR(50),
    RENT_PICKUP_DATETIME DATETIME,
    RENT_PICKUP_LOCATION VARCHAR(255),
    RENT_DROPOFF_DATETIME DATETIME,
    RENT_DROPOFF_LOCATION VARCHAR(255),
    RENTAL_STATUS VARCHAR(20),
    RENT_TOTAL_PRICE DECIMAL(10, 2),
    FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (ASSIGNED_DRIVER_ID) REFERENCES DRIVER(DRIVER_ID)
);

-- RENT_PENALTY Table
CREATE TABLE RENT_PENALTY (
    RP_ID INT AUTO_INCREMENT PRIMARY KEY,
    RP_1 DECIMAL(10, 2),
    RP_2 DECIMAL(10, 2),
    RP_3 DECIMAL(10, 2)
);

-- PAYMENT Table
CREATE TABLE PAYMENT (
    PAY_ID INT AUTO_INCREMENT PRIMARY KEY,
    RENTAL_ID INT,
    RP_ID INT,
    PAY_TYPE VARCHAR(50),
    PAY_METHOD VARCHAR(50),
    PAY_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PAY_RENTAL_CHARGE DECIMAL(10, 2),
    PAY_PICKUP_CHARGE DECIMAL(10, 2),
    PAY_DROPOFF_CHARGE DECIMAL(10, 2),
    PAY_RESERVATION_FEE DECIMAL(10, 2),
    PAY_TOTAL_DUE DECIMAL(10, 2),
    PAY_AMOUNT_PAID DECIMAL(10, 2),
    PAY_BALANCE_DUE DECIMAL(10, 2),
    PAY_STATUS VARCHAR(20),
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTAL(RENTAL_ID),
    FOREIGN KEY (RP_ID) REFERENCES RENT_PENALTY(RP_ID)
);

-- RECEIPT Table
CREATE TABLE RECEIPT (
    RECEIPT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PAY_ID INT,
    RECEIPT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RECEIPT_AMOUNT_PAID DECIMAL(10, 2),
    RECEIPT_BALANCE_DUE DECIMAL(10, 2),
    PAY_STATUS VARCHAR(20),
    FOREIGN KEY (PAY_ID) REFERENCES PAYMENT(PAY_ID)
);
